app/models/__init__.py
from app.models.nota import Nota

app/models/nota.py
from app import db

class Nota(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    titulo = db.Column(db.String(100), nullable=False)
    descripcion = db.Column(db.String(200), nullable=False)

app/__init__.py
import os
from flask import Flask, request, jsonify, render_template, redirect, url_for
from flask_sqlalchemy import SQLAlchemy

from dotenv import load_dotenv 

#Cargar las variables de entorno
load_dotenv()

#crear instancia
app =  Flask(__name__)

# Configuración de la base de datos PostgreSQL
app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('DATABASE_URL')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)

# Importar modelos para que SQLAlchemy los reconozca
from app.models import Nota

# Importar y registrar blueprints
from app.routes.nota import nota_bp

# Crear las tablas si no existen
with app.app_context():
    db.create_all()
    
app.register_blueprint(nota_bp, url_prefix='/notas')


#Ruta principal home
@app.route('/')
def index():
    #return 'Hola mundo'
    notas = Nota.query.all()
    return render_template('index.html', notas=notas)

app/routes/nota.py
from flask import Blueprint, render_template, request, redirect, url_for
from app import db
from app.models import Nota

nota_bp = Blueprint('notas', __name__)

@nota_bp.route('/')
def listar_notas():
    notas = Nota.query.all()
    return render_template('index.html', notas=notas)

@nota_bp.route('/nuevo', methods=['GET', 'POST'])
def nueva_nota():
    if request.method == 'POST':
        titulo = request.form['titulo']
        descripcion = request.form['descripcion']
        
        nuevo = Nota(titulo=titulo, descripcion=descripcion)
        db.session.add(nuevo)
        db.session.commit()
        return redirect(url_for('notas.listar_notas'))
    return render_template('form.html')

@nota_bp.route('/editar/<int:id>', methods=['GET', 'POST'])
def editar_nota(id):
    nota = Nota.query.get_or_404(id)
    if request.method == 'POST':
        nota.titulo = request.form['titulo']
        nota.descripcion = request.form['descripcion']
        db.session.commit()
        return redirect(url_for('notas.listar_notas'))
    return render_template('form.html', nota=nota)

@nota_bp.route('/eliminar/<int:id>')
def eliminar_nota(id):
    contacto = Nota.query.get_or_404(id)
    db.session.delete(contacto)
    db.session.commit()
    return redirect(url_for('notas.listar_notas'))

app/templates/base.html
<!DOCTYPE html>
<html class="theme-light" style="background-color: #161405;">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Notas</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css">
    <script src="https://kit.fontawesome.com/ee9903c79f.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@700&display=swap" rel="stylesheet">




</head>
  <body >
    <header>
        <br>
        <h1 class="title has-text-centered is-1" style="font-family: 'Merriweather', serif ;  color:#b6fd02">
            <i class="fa-regular fa-clipboard"></i>  Notas 2.0.0
          </h1>
          <br>
    </header>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
  </body>
</html>

app/templates/form.html
{% extends 'base.html' %}
{% block content %}
<div class="columns">
    <div class="column is-offset-3 is-6">
        <div class="card">
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4">Nota</p>
                    </div>
                </div>
                <div class="content">
                    <form method="POST">
                        <div class="field">
                            <label class="label">Titulo:</label>
                            <div class="control has-icons-left has-icons-right">
                                <input class="input is-link" type="text" name="titulo"
                                    value="{{ nota.titulo if nota else '' }}">
                                <span class="icon is-small is-left">
                                    <i class="fa-regular fa-note-sticky"></i>
                                </span>
                            </div>
                        </div>
                        <div class="field">
                            <label class="label">Descripción</label>
                            <div class="control">
                                <textarea class="textarea is-link" name="descripcion">{{ nota.descripcion if nota else '' }}</textarea>
                            </div>
                        </div>


                        <button class="button is-link is-outlined" type="submit"><i
                                class="fa-solid fa-floppy-disk"></i>&nbsp;Guardar</button>
                        <a class="button is-danger is-outlined" href="{{ url_for('notas.listar_notas') }}"><i
                                class="fa-solid fa-arrow-left"></i>&nbsp;Regresar</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="columns">
  <div class="column is-offset-3 is-6">
    <a href="{{ url_for('notas.nueva_nota') }}" class="button is-link is-outlined"><i class="fa-solid fa-plus"></i>
      &nbsp;
      Agregar nota</a>
    <br><br>
    {% for c in notas %}
    <div class="card">
      <div class="card-content">
        <div class="media">
          <div class="media-left">
            <figure class="image is-48x48">
              <img src="https://cdn-icons-png.flaticon.com/256/1024/1024824.png"
                alt="Placeholder image" />
            </figure>
          </div>
          <div class="media-content">
            <p class="title is-4">{{ c.titulo }}</p>
            <p class="subtitle is-6"> {{ c.descripcion }}</p>
          </div>
        </div>
        <footer class="card-footer">
          <a href="{{ url_for('notas.editar_nota', id=c.id) }}"" class=" card-footer-item">Editar</a>
          <a href="{{ url_for('notas.eliminar_nota', id=c.id) }}" class="card-footer-item">Eliminar</a>
        </footer>

      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}